-- SQL Schema for Weekend Mission MVP

-- Create missions table
create table if not exists public.missions (
    id bigint generated by default as identity primary key,
    code text unique not null,
    title text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create weekend_entries table
create table if not exists public.weekend_entries (
    id uuid default gen_random_uuid() primary key,
    device_id uuid not null,
    display_name text not null,
    mission_id bigint references public.missions(id) on delete cascade not null,
    status text not null check (status in ('Assigned', 'Completed')),
    weekend_key text not null,
    assigned_at timestamp with time zone default timezone('utc'::text, now()) not null,
    completed_at timestamp with time zone,
    proof_text text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    -- Ensure a device can only have one entry per weekend
    constraint unique_device_weekend unique (device_id, weekend_key)
);

-- Create indexes for fast queries
create index if not exists idx_weekend_entries_device_weekend on public.weekend_entries(device_id, weekend_key);

-- Enable Row Level Security (RLS)
alter table public.missions enable row level security;
alter table public.weekend_entries enable row level security;

-- Policies for missions (allow public read access to active missions)
create policy "Allow public read access to active missions"
on public.missions for select
using (active = true);

create policy "Allow authenticated admin select all missions"
on public.missions for select
using (auth.role() = 'authenticated');

create policy "Allow authenticated admin update missions"
on public.missions for update
using (auth.role() = 'authenticated');


-- Policies for weekend_entries (allow public select, insert, and update)
create policy "Allow public select from weekend_entries"
on public.weekend_entries for select
using (true);

create policy "Allow public insert to weekend_entries"
on public.weekend_entries for insert
with check (true);

create policy "Allow public update to weekend_entries"
on public.weekend_entries for update
using (true);

-- Custom PostgreSQL function (RPC) to retrieve a random unseen mission for a device
create or replace function get_random_unseen_mission(p_device_id uuid)
returns table (
    id bigint,
    code text,
    title text,
    description text,
    active boolean
) language plpgsql as $$
begin
    -- 1. Try to get an active mission that hasn't been assigned to this device yet
    return query
    select m.id, m.code, m.title, m.description, m.active
    from public.missions m
    where m.active = true
      and m.id not in (
          select we.mission_id 
          from public.weekend_entries we 
          where we.device_id = p_device_id
      )
    order by random()
    limit 1;
    
    -- 2. If no unseen missions exist (all active missions have been seen), fallback to any active mission
    if not found then
        return query
        select m.id, m.code, m.title, m.description, m.active
        from public.missions m
        where m.active = true
        order by random()
        limit 1;
    end if;
end;
$$;

-- Insert 50 default starter missions
insert into public.missions (id, code, title, description, active) values
(1, 'WM-001', 'Clear One Backlog', 'Finish one thing you''ve been postponing for a long time.', true),
(2, 'WM-002', 'Send That Message', 'Send the message you''ve been thinking about sending.', true),
(3, 'WM-003', 'Finish the Draft', 'Complete something that''s already 80% finished.', true),
(4, 'WM-004', 'Clean Your Digital Space', 'Organize one folder, drive, desktop or inbox.', true),
(5, 'WM-005', 'Remove One Distraction', 'Delete, uninstall or mute one thing that constantly wastes your time.', true),
(6, 'WM-006', 'Learn Something New', 'Spend time learning something you''ve never explored before.', true),
(7, 'WM-007', 'Teach Someone', 'Explain something you know to another person.', true),
(8, 'WM-008', 'Fix Something', 'Repair, improve or organize something that''s been annoying you.', true),
(9, 'WM-009', 'Reach Out', 'Reconnect with someone you haven''t spoken to in a while.', true),
(10, 'WM-010', 'Appreciate Someone', 'Thank someone who deserves appreciation.', true),
(11, 'WM-011', 'Make Someone''s Day', 'Do something kind without expecting anything back.', true),
(12, 'WM-012', 'Leave Your Comfort Zone', 'Do one thing you''ve been avoiding because it feels uncomfortable.', true),
(13, 'WM-013', 'Finish Before Midnight', 'Complete one pending task before today ends.', true),
(14, 'WM-014', 'Build Something', 'Create something small from start to finish.', true),
(15, 'WM-015', 'Share Your Work', 'Publish or share something you''ve created.', true),
(16, 'WM-016', 'Organize Your Space', 'Make one physical space noticeably better than before.', true),
(17, 'WM-017', 'Delete the Clutter', 'Remove unnecessary files, photos or apps.', true),
(18, 'WM-018', 'Read With Intention', 'Read something that genuinely teaches you something useful.', true),
(19, 'WM-019', 'Write Your Thoughts', 'Write about whatever has been on your mind recently.', true),
(20, 'WM-020', 'Plan Next Week', 'Create a realistic plan for the coming week.', true),
(21, 'WM-021', 'Learn From Someone', 'Watch, read or listen to someone more experienced than you.', true),
(22, 'WM-022', 'Help Without Being Asked', 'Offer help before someone asks for it.', true),
(23, 'WM-023', 'Say No', 'Say no to something that isn''t worth your time.', true),
(24, 'WM-024', 'Try Something Different', 'Break one routine today.', true),
(25, 'WM-025', 'Finish One Chapter', 'Complete one section, lesson or chapter of something you''re learning.', true),
(26, 'WM-026', 'Improve Your Setup', 'Improve your workspace or study environment.', true),
(27, 'WM-027', 'Reflect', 'Think about one thing you could have done better this week.', true),
(28, 'WM-028', 'Take Initiative', 'Start something instead of waiting for permission.', true),
(29, 'WM-029', 'Reduce Screen Time', 'Spend meaningful time away from unnecessary screens.', true),
(30, 'WM-030', 'Learn a Useful Tool', 'Discover one tool, app or resource that improves your workflow.', true),
(31, 'WM-031', 'Document Your Progress', 'Take a picture, note or screenshot of something you''ve improved.', true),
(32, 'WM-032', 'Complete a Personal Goal', 'Finish one personal objective you''ve delayed.', true),
(33, 'WM-033', 'Ask a Good Question', 'Have one meaningful conversation by asking a thoughtful question.', true),
(34, 'WM-034', 'Leave Something Better', 'Improve a place, document or situation before leaving it.', true),
(35, 'WM-035', 'Take the First Step', 'Start something you''ve been waiting to begin.', true),
(36, 'WM-036', 'Do the Difficult Thing First', 'Complete your hardest task before everything else.', true),
(37, 'WM-037', 'Declutter Your Mind', 'Write down everything currently occupying your thoughts.', true),
(38, 'WM-038', 'Inspire Someone', 'Share something useful with another person.', true),
(39, 'WM-039', 'Finish What You Started', 'Return to something unfinished and complete it.', true),
(40, 'WM-040', 'Create Instead of Consume', 'Spend more time creating than consuming today.', true),
(41, 'WM-041', 'One Hour of Focus', 'Give one uninterrupted hour to something important.', true),
(42, 'WM-042', 'Learn by Doing', 'Instead of reading about it, actually try it.', true),
(43, 'WM-043', 'Improve One Habit', 'Make one small improvement to an existing habit.', true),
(44, 'WM-044', 'Be Curious', 'Explore a topic you''ve always wanted to understand.', true),
(45, 'WM-045', 'Solve One Problem', 'Identify one problem in your life and make it slightly better.', true),
(46, 'WM-046', 'Do Something You''ll Thank Yourself For', 'Complete something that makes tomorrow easier.', true),
(47, 'WM-047', 'Capture a Win', 'Celebrate one thing you accomplished this week.', true),
(48, 'WM-048', 'Reset', 'Spend time preparing yourself for a better week ahead.', true),
(49, 'WM-049', 'Do What You''ve Been Avoiding', 'Stop thinking about it. Start it.', true),
(50, 'WM-050', 'Leave No Regrets', 'Before the weekend ends, finish one thing you''ll be proud you didn''t postpone.', true)
on conflict (id) do update set 
    code = excluded.code,
    title = excluded.title,
    description = excluded.description,
    active = excluded.active;

-- Create weekend_settings table
create table if not exists public.weekend_settings (
    key text primary key,
    value text not null
);

-- Enable RLS
alter table public.weekend_settings enable row level security;

-- Policies for weekend_settings
create policy "Allow public read access to weekend_settings"
on public.weekend_settings for select
using (true);

create policy "Allow authenticated admin write to weekend_settings"
on public.weekend_settings for insert
with check (auth.role() = 'authenticated');

create policy "Allow authenticated admin update to weekend_settings"
on public.weekend_settings for update
using (auth.role() = 'authenticated');

-- Insert default overrides
insert into public.weekend_settings (key, value)
values ('weekend_override', 'automatic')
on conflict (key) do nothing;
