-- SQL Schema for Weekend Mission MVP

-- Create missions table
create table if not exists public.missions (
    id bigint generated by default as identity primary key,
    code text unique not null,
    title text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create weekend_entries table
create table if not exists public.weekend_entries (
    id uuid default gen_random_uuid() primary key,
    device_id uuid not null,
    display_name text not null,
    mission_id bigint references public.missions(id) on delete cascade not null,
    status text not null check (status in ('Assigned', 'Completed')),
    weekend_key text not null,
    assigned_at timestamp with time zone default timezone('utc'::text, now()) not null,
    completed_at timestamp with time zone,
    proof_text text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    -- Ensure a device can only have one entry per weekend
    constraint unique_device_weekend unique (device_id, weekend_key)
);

-- Create indexes for fast queries
create index if not exists idx_weekend_entries_device_weekend on public.weekend_entries(device_id, weekend_key);

-- Enable Row Level Security (RLS)
alter table public.missions enable row level security;
alter table public.weekend_entries enable row level security;

-- Policies for missions (allow public read access to active missions)
create policy "Allow public read access to active missions"
on public.missions for select
using (active = true);

create policy "Allow authenticated admin select all missions"
on public.missions for select
using (auth.role() = 'authenticated');

create policy "Allow authenticated admin update missions"
on public.missions for update
using (auth.role() = 'authenticated');


-- Policies for weekend_entries (allow public select, insert, and update)
create policy "Allow public select from weekend_entries"
on public.weekend_entries for select
using (true);

create policy "Allow public insert to weekend_entries"
on public.weekend_entries for insert
with check (true);

create policy "Allow public update to weekend_entries"
on public.weekend_entries for update
using (true);

-- Custom PostgreSQL function (RPC) to retrieve a random unseen mission for a device
create or replace function get_random_unseen_mission(p_device_id uuid)
returns table (
    id bigint,
    code text,
    title text,
    description text,
    active boolean
) language plpgsql as $$
begin
    -- 1. Try to get an active mission that hasn't been assigned to this device yet
    return query
    select m.id, m.code, m.title, m.description, m.active
    from public.missions m
    where m.active = true
      and m.id not in (
          select we.mission_id 
          from public.weekend_entries we 
          where we.device_id = p_device_id
      )
    order by random()
    limit 1;
    
    -- 2. If no unseen missions exist (all active missions have been seen), fallback to any active mission
    if not found then
        return query
        select m.id, m.code, m.title, m.description, m.active
        from public.missions m
        where m.active = true
        order by random()
        limit 1;
    end if;
end;
$$;

-- Insert 50 default starter missions
insert into public.missions (id, code, title, description, active) values
(1, 'WM-001', 'Just Begin', 'Start the thing you''ve been avoiding. Don''t think about finishing it—just begin.', true),
(2, 'WM-002', 'Open the Project', 'Open something you''ve been delaying and make one meaningful improvement.', true),
(3, 'WM-003', 'Five Minute Rule', 'Commit to working for at least five focused minutes. Keep going if you want.', true),
(4, 'WM-004', 'Remove One Blocker', 'Solve one obstacle that''s preventing your progress.', true),
(5, 'WM-005', 'Finish One Small Task', 'Choose one unfinished task and complete it before starting anything new.', true),
(6, 'WM-006', 'Progress Over Perfection', 'Move your work forward instead of making it perfect.', true),
(7, 'WM-007', 'Ship Something', 'Publish, submit, push, upload, send, or share something you''ve been working on.', true),
(8, 'WM-008', 'Build Instead of Consume', 'Spend your time creating instead of endlessly consuming content.', true),
(9, 'WM-009', 'Complete a Draft', 'Finish a rough version instead of waiting for the perfect one.', true),
(10, 'WM-010', 'Improve Yesterday', 'Take something you created earlier and make it better.', true),
(11, 'WM-011', 'Single Task Mode', 'Work on only one objective until you''ve made visible progress.', true),
(12, 'WM-012', 'Deep Focus', 'Remove distractions and focus completely on one task.', true),
(13, 'WM-013', 'Stay With It', 'Don''t switch projects until you''ve completed one meaningful step.', true),
(14, 'WM-014', 'Beat Resistance', 'Do the task you''ve been mentally avoiding the most.', true),
(15, 'WM-015', 'Keep Going', 'Continue working for a little longer after you feel like stopping.', true),
(16, 'WM-016', 'Close an Open Loop', 'Finish something that''s been left incomplete.', true),
(17, 'WM-017', 'Tiny Milestone', 'Reach one small milestone before ending today''s session.', true),
(18, 'WM-018', 'Simplify Something', 'Make part of your work cleaner, simpler, or easier to understand.', true),
(19, 'WM-019', 'Solve One Problem', 'Identify one issue and fix it today.', true),
(20, 'WM-020', 'Visible Progress', 'End today with something you can clearly point to as progress.', true),
(21, 'WM-021', 'Learn With Purpose', 'Learn something directly related to what you''re building.', true),
(22, 'WM-022', 'Apply What You Learned', 'Use a new idea immediately instead of just reading about it.', true),
(23, 'WM-023', 'Practice Deliberately', 'Repeat a skill you''re trying to improve until you notice progress.', true),
(24, 'WM-024', 'Experiment', 'Try one new approach without worrying if it works.', true),
(25, 'WM-025', 'Document Your Learning', 'Write down one useful thing you''ll remember later.', true),
(26, 'WM-026', 'Ask for Feedback', 'Show your work to someone and ask for honest feedback.', true),
(27, 'WM-027', 'Share Your Progress', 'Tell someone what you''ve completed today.', true),
(28, 'WM-028', 'Ask One Question', 'Reach out when you''re stuck instead of staying blocked.', true),
(29, 'WM-029', 'Have the Conversation', 'Send the message you''ve been postponing.', true),
(30, 'WM-030', 'Take the Uncomfortable Step', 'Do one action you''ve been avoiding because it feels difficult.', true),
(31, 'WM-031', 'Minimum Viable Progress', 'Complete the smallest meaningful version of today''s work.', true),
(32, 'WM-032', 'Protect the Streak', 'Show up today, even if your progress is small.', true),
(33, 'WM-033', 'Don''t Restart', 'Continue an existing project instead of beginning a new one.', true),
(34, 'WM-034', 'Work First', 'Finish meaningful work before entertainment.', true),
(35, 'WM-035', 'Earn the Break', 'Complete one important task before taking a long break.', true),
(36, 'WM-036', 'One More Iteration', 'Improve your work one more time before stopping.', true),
(37, 'WM-037', 'Polish One Detail', 'Refine one small part that makes the whole thing better.', true),
(38, 'WM-038', 'Prepare Tomorrow', 'Leave your work in a state that''s easy to continue tomorrow.', true),
(39, 'WM-039', 'Create Momentum', 'Do something that makes your next session easier.', true),
(40, 'WM-040', 'End With Intention', 'Stop only after you''ve completed a meaningful checkpoint.', true),
(41, 'WM-041', 'Build the Habit', 'Show up because habits beat motivation.', true),
(42, 'WM-042', 'Stay Consistent', 'Work today regardless of how motivated you feel.', true),
(43, 'WM-043', 'Keep the Promise', 'Finish the task you promised yourself you''d do.', true),
(44, 'WM-044', 'Push the Boundary', 'Go slightly beyond what you originally planned.', true),
(45, 'WM-045', 'Make It Real', 'Turn one idea into something tangible.', true),
(46, 'WM-046', 'Clear the Backlog', 'Complete one task that''s been sitting on your list for too long.', true),
(47, 'WM-047', 'Reduce Friction', 'Make one change that helps you work more easily next time.', true),
(48, 'WM-048', 'Build Momentum', 'Complete one action that naturally leads to the next.', true),
(49, 'WM-049', 'Leave It Better', 'Improve something you touched today before walking away.', true),
(50, 'WM-050', 'Win the Day', 'Finish today knowing you moved your life forward, even if only by one step.', true)
on conflict (id) do update set 
    code = excluded.code,
    title = excluded.title,
    description = excluded.description,
    active = excluded.active;

-- Create weekend_settings table
create table if not exists public.weekend_settings (
    key text primary key,
    value text not null
);

-- Enable RLS
alter table public.weekend_settings enable row level security;

-- Policies for weekend_settings
create policy "Allow public read access to weekend_settings"
on public.weekend_settings for select
using (true);

create policy "Allow authenticated admin write to weekend_settings"
on public.weekend_settings for insert
with check (auth.role() = 'authenticated');

create policy "Allow authenticated admin update to weekend_settings"
on public.weekend_settings for update
using (auth.role() = 'authenticated');

-- Insert default overrides
insert into public.weekend_settings (key, value)
values ('weekend_override', 'automatic')
on conflict (key) do nothing;
